# Required
version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: doc/source/conf.py

formats: []

python:
  version: 3.7
  install:
    - requirements: doc/requirements.txt
    - method: setuptools
      path: GPflow
